### ISSUE TITLE
Deleted message remains visible in message list

### ISSUE THREAD

**Issue by HelmutL** [thunderbird/thunderbird-android#10243]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

16.0b2

### Where did you get the app from?

Other

### Android version

15

### Device model

Xiaomi 14

### Steps to reproduce

show message list
click on top message to show it
delete the message by click on the trashbin -> returns to message list

### Expected behavior

deleted message should disappear from list

### Actual behavior

the deleted message remains visible in the message list until the next refresh or sync. The message looks as if it had not been read, but it cannot be selected again. Actually, it has been correctly moved to trash.

This happens only if the concerned message is th top one in the list.

https://github.com/user-attachments/assets/30322137-5529-4f86-ad32-d7619cf57ae1

**Comment by abelj4n** [comment]
Having the same issue with thunderbird app version 16.02b on Android 16 (Samsung Galaxy S25 Ultra). 
It's not only happening when deleting a message, but also when moving a message to a different folder. 
For me it's not limited to just one message, but can happen for multiple ones which all stay visible and unclickable in the unified inbox list until you actively refresh it (via pull-down action).

**Comment by platform34** [comment]
Similar issue also reported on SUMO: https://support.mozilla.org/en-US/questions/1555481

I'm able to replicate these issues on beta v16.0b3. I don't observe them on v14.
They only seems to occur within the Unified Inbox. 

An alternative way to observe.

1. Select Unified Inbox.
2. Mark a message as new / unread.
3. Open the unread email, return to the message list.
4. Observe message still shows unread (bold status). Is should be marked read.
5. The correct status is displayed after scrolling the list, synchronizing or navigating to a different account.

Between point 4 & 5, other emails don't update their visual status when selected or marked read/unread with a swipe or long press.

**Comment by ClapTrap1305** [comment]
Same issue. 16.0b3 Pixel 7a

Im also effected  from all reported behaviours before

**Comment by siffegh** [comment]
Same, TB 14.0/LG G6/Android 9.

**Comment by s-martin** [comment]
Same issue and all described behaviors with 16.0b3 Pixel 7

**Comment by coreycb** [comment]
@wmontwe @rafaeltonholo Do you have any ideas on this?

**Comment by uniquePWD** [comment]
It seems to be either a caching issue or a failure to initialise a message list update introduced in v16. It definitely shouldn't be excessively hard to track down.

**Comment by rafaeltonholo** [comment]
> [@wmontwe](https://github.com/wmontwe) [@rafaeltonholo](https://github.com/rafaeltonholo) Do you have any ideas on this?

I'm not sure what could have caused this. We need to investigate what could have introduced this behaviour in v16. I will try to git bisect to find out what commit could have caused that issue

**Comment by aetherrauschen** [comment]
I have the same issue in 16.04b with a single account setup, i.e. no unified inbox. It not only happens for deleted messages, but also for messages that are moved to another folder.

**Comment by coreycb** [comment]
Marking confirmed since there are many reports

**Comment by quite** [comment]
This was solved for me in K9 16.1. Now in K9 17.0 this is back. At least for the specific case:
- unread (bold font) mail at the top of the list
- tap that mail
- mail is shown
- tap back
- the mail is still unread
- slide the list up and down slightly
- the mail is now marked as read

**Comment by HelmutL** [comment]
I am running TB 18.0b2.
For me, it the problem was never solved completely. But it happens far less often now (I would estimate 80 or 90% are ok). However, I heve not found a rule that causes it to happen.

**Comment by coreycb** [comment]
> This was solved for me in K9 16.1. Now in K9 17.0 this is back. At least for the specific case:
> 
>     * unread (bold font) mail at the top of the list
> 
>     * tap that mail
> 
>     * mail is shown
> 
>     * tap back
> 
>     * the mail is still unread
> 
>     * slide the list up and down slightly
> 
>     * the mail is now marked as read

I was unable to recreate this on 17.0. You're using the unified inbox?
Any more clues to help recreate are welcomed.

**Comment by quite** [comment]
> > This was solved for me in K9 16.1. Now in K9 17.0 this is back. At least for the specific case:
> > ```
> > * unread (bold font) mail at the top of the list
> > 
> > * tap that mail
> > 
> > * mail is shown
> > 
> > * tap back
> > 
> > * the mail is still unread
> > 
> > * slide the list up and down slightly
> > 
> > * the mail is now marked as read
> > ```
> 
> I was unable to recreate this on 17.0. You're using the unified inbox? Any more clues to help recreate are welcomed.

I tried it again now, reproduced just like in the above.

Not unified inbox. This is motorola g82 with their android 13.

**Comment by quite** [comment]
> I tried it again now, reproduced just like in the above.
> 
> Not unified inbox. This is motorola g82 with their android 13.

I can note that i was always tapping the back button (◀) in the bottom "3-button navigation bar".

I now tried tapping the arrow `<-` on the left side in the "app top bar". This usually also provokes this issue, but it does seem to sometimes result in correct read-marking right away, given the above procedure.

**Comment by HelmutL** [comment]
Please reopen this bug

**Comment by scaidermern** [comment]
I also encounter this issue again in version 17.0 although it was already fixed in 16.1.

Unified inbox here, version from F-Droid.. I can't reproduce it reliably though. Sometimes it appears, sometimes it doesn't.

**Comment by HelmutL** [comment]
Reopened as bug #10731

**Comment by cremor** [comment]
I can also confirm that this still happens on app version 17. For me it only started recently, maybe only **with** version 17.

I can reproduce the problem most of the time by this steps:
1. Open the unified inbox (from the home screen widget).
2. Open a new/unread mail to read it (which marks it as read).
3. Either:
   - Delete the mail.
      OR
   - Swipe left/right to a different new/unread mail (in this case you can repeat step 3 multiple times).
4. Go back to the message list (via the system gesture).
5. Notice that the read and/or deleted mail(s) are still visible and bold (unread) in the message list.
6. Tap once anywhere in empty space in the message list.
7. Only now the list is refreshed.
