### ISSUE TITLE
Deleting mail from notification does not dismiss notification

### ISSUE THREAD

**Issue by gadgetfan10** [thunderbird/thunderbird-android#1588]
**Expected behavior:** When using the delete button in a new mail notification to delete a message, the the message should be deleted and the notification should disappear.

**Actual behavior:** The message is deleted, but sometimes the notification persists. This only happens infrequently, and I have not yet found a way to reproduce it. I'm not sure if this is related to #1273.

K-9 Mail version: 5.111

Android version: 6.0 (Verizon LG G4, stock)

Account type: IMAP

**Comment by philipwhiuk** [comment]
This works for me on 7.0 as of unreleased (beta or otherwise) changes to Notifications in master.

Note that if it doesn't work in 7.1.1 for me that's not necessarily a bug right now - K-9 may behave in unexpected ways on unreleased previews - I'm not saying we won't fix issues on 7.1.1 but if it's behaving differently we'd want to wait until it looked likely to remain that way when it was released to the general public.

**Comment by mittwinter** [comment]
So, a few days ago, I received the update to K-9 version 5.115. Should this issue be fixed in this version? If so, it is unfortunately **not** fixed for me, as the issue still persists after the update. I'm on Android 6.0.1 by the way.

(PS: Sorry for my duplicate issue #1762 on this, I thought that I'd searched thoroughly before creating a new one.)

**Comment by mruwek** [comment]
It's still there also for me with K-9 version 5.115 and Android 7.1 (CM-14.1 official nightly for Moto G 2015).

**Comment by philipwhiuk** [comment]
@mittwinter if you delete the same message from the inbox does it get deleted.

all - it would be great if we could get some device logs for this - given I can't reproduce it on my device. Stable released versions of Android preferable but I'll look at any log.

**Comment by woj-tek** [comment]
Not sure whether this thread or #1822 fits better but I just stumbled against the same issue in 5.200 - I got an e-main, it triggered notification, I hit "mark as read" and nothing happened. I've noticed that the mail actually got marked as read but the notification wasn't dismissed.

**Comment by philipwhiuk** [comment]
@cketti Do you think #2169 will fix this one too?

**Comment by cketti** [comment]
Unlikely. With the bug fixed in #2169 notification actions weren't performed at all.

**Comment by chris-y** [comment]
Confirmed that this/#1822 is still an issue in 5.205 - Android 7.0, so #2169 does not seem to have fixed it.

**Comment by kpyfan** [comment]
I have a Pixel 2XL on Android 10 that is running into a similar issue, but with marking the email as read. Pressing the button does mark the email as read, but does not clear the notification (and there's no animated feedback on the "Mark As Read" button as I click it)

**Comment by syntech16** [comment]
I've had this problem intermittently for a while now, just like @kpyfan said, and today I've been able to reproduce it again. I've received an e-mail in K-9 and clicking on "Mark as read" marks it as read on the app, but keeps the notification on the notification list.

I'm running K-9 Mail 5.721 on a OnePlus 5T with Android 9, but it has also happened to me with previous versions of the app. I'll add the logs that are shown in Logcat when I press "Mark as read":

```
2020-10-18 01:15:51.802 4560-4560/? I/NotificationActionService: NotificationActionService started with startId = 4
2020-10-18 01:15:51.803 4560-4560/? I/NotificationActionService: NotificationActionService marking messages as read
2020-10-18 01:15:51.824 4560-4560/? V/LockableDatabase: LockableDatabase: Transaction ended, took 6 ms / com.fsck.k9.mailstore.LocalFolder.setFlags(LocalFolder.java:1509)
2020-10-18 01:15:51.835 4560-4578/? I/MessagingController: Running command 'queueSetFlag', seq = 104 (background priority)
2020-10-18 01:15:51.839 4560-4578/? I/MessagingController:  Command 'queueSetFlag' completed
2020-10-18 01:15:51.839 4560-4578/? I/MessagingController: Running command 'processPendingCommands', seq = 105 (background priority)
2020-10-18 01:15:51.840 4560-4578/? D/MessagingController: Processing pending command 'com.fsck.k9.controller.MessagingControllerCommands$PendingSetFlag@6889987'
2020-10-18 01:15:51.841 4560-4578/? V/ImapConnection: conn182313470>>> 22 NOOP
2020-10-18 01:15:51.956 4560-4578/? V/ImapResponseParser: conn182313470<<<#22# [OK, NOOP completed.]
2020-10-18 01:15:51.957 4560-4578/? V/ImapConnection: conn182313470>>> 23 SELECT "INBOX"
2020-10-18 01:15:52.057 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [OK, [CLOSED], Previous mailbox closed.]
2020-10-18 01:15:52.058 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $Forwarded]]
2020-10-18 01:15:52.058 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [OK, [PERMANENTFLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $Forwarded, \*]], Flags permitted.]
2020-10-18 01:15:52.059 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [130, EXISTS]
2020-10-18 01:15:52.059 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [0, RECENT]
2020-10-18 01:15:52.059 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [OK, [UIDVALIDITY, 1588202730], UIDs valid]
2020-10-18 01:15:52.060 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [OK, [UIDNEXT, 132], Predicted next UID]
2020-10-18 01:15:52.060 4560-4578/? V/ImapResponseParser: conn182313470<<<#null# [OK, [HIGHESTMODSEQ, 268], Highest]
2020-10-18 01:15:52.061 4560-4578/? V/ImapResponseParser: conn182313470<<<#23# [OK, [READ-WRITE], Select completed (0.000 secs).]
2020-10-18 01:15:52.061 4560-4578/? D/ImapFolder: Got untagged EXISTS with value 130 for av@p:INBOX/MessagingController/conn182313470
2020-10-18 01:15:52.062 4560-4578/? D/ImapFolder: Got UidNext = 132 for av@p:INBOX/MessagingController/conn182313470
2020-10-18 01:15:52.064 4560-4578/? V/ImapConnection: conn182313470>>> 24 NOOP
2020-10-18 01:15:52.150 4560-4578/? V/ImapResponseParser: conn182313470<<<#24# [OK, NOOP completed.]
2020-10-18 01:15:52.152 4560-4578/? V/ImapConnection: conn182313470>>> 25 UID STORE 131 +FLAGS.SILENT (\Seen)
2020-10-18 01:15:52.247 4560-4578/? V/ImapResponseParser: conn182313470<<<#25# [OK, Store completed.]
2020-10-18 01:15:52.255 4560-4578/? D/MessagingController: Done processing pending command 'com.fsck.k9.controller.MessagingControllerCommands$PendingSetFlag@6889987'
2020-10-18 01:15:52.255 4560-4578/? I/MessagingController:  Command 'processPendingCommands' completed
2020-10-18 01:15:52.255 4560-4578/? I/MessagingController: Running command 'processPendingCommands', seq = 106 (background priority)
2020-10-18 01:15:52.256 4560-4578/? I/MessagingController:  Command 'processPendingCommands' completed
```

Some other times, the button works well. For those times that it is correctly dismissed, the logs are the following:

```
2020-10-18 01:49:23.625 4560-4560/? I/NotificationActionService: NotificationActionService started with startId = 9
2020-10-18 01:49:23.626 4560-4560/? I/NotificationActionService: NotificationActionService marking messages as read
2020-10-18 01:49:23.635 4560-4560/? V/LockableDatabase: LockableDatabase: Transaction ended, took 5 ms / com.fsck.k9.mailstore.LocalFolder.setFlags(LocalFolder.java:1509)
2020-10-18 01:49:23.652 4560-4578/? I/MessagingController: Running command 'queueSetFlag', seq = 208 (background priority)
2020-10-18 01:49:23.661 4560-4578/? I/MessagingController:  Command 'queueSetFlag' completed
2020-10-18 01:49:23.661 4560-4578/? I/MessagingController: Running command 'processPendingCommands', seq = 209 (background priority)
2020-10-18 01:49:23.662 4560-4578/? D/MessagingController: Processing pending command 'com.fsck.k9.controller.MessagingControllerCommands$PendingSetFlag@48b983c'
2020-10-18 01:49:23.662 4560-4578/? V/ImapConnection: conn79097420>>> 24 NOOP
2020-10-18 01:49:23.684 4560-4560/? E/Choreographer: skip doframe for com.fsck.k9
2020-10-18 01:49:23.736 4560-4578/? V/ImapResponseParser: conn79097420<<<#24# [OK, NOOP completed.]
2020-10-18 01:49:23.737 4560-4578/? V/ImapConnection: conn79097420>>> 25 SELECT "INBOX"
2020-10-18 01:49:23.787 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [OK, [CLOSED], Previous mailbox closed.]
2020-10-18 01:49:23.787 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $Forwarded]]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [OK, [PERMANENTFLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $Forwarded, \*]], Flags permitted.]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [131, EXISTS]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [1, RECENT]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [OK, [UNSEEN, 131], First unseen.]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [OK, [UIDVALIDITY, 1588202730], UIDs valid]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [OK, [UIDNEXT, 133], Predicted next UID]
2020-10-18 01:49:23.788 4560-4578/? V/ImapResponseParser: conn79097420<<<#null# [OK, [HIGHESTMODSEQ, 271], Highest]
2020-10-18 01:49:23.789 4560-4578/? V/ImapResponseParser: conn79097420<<<#25# [OK, [READ-WRITE], Select completed (0.000 secs).]
2020-10-18 01:49:23.789 4560-4578/? D/ImapFolder: Got untagged EXISTS with value 131 for av@p:INBOX/MessagingController/conn79097420
2020-10-18 01:49:23.789 4560-4578/? D/ImapFolder: Got UidNext = 133 for av@p:INBOX/MessagingController/conn79097420
2020-10-18 01:49:23.789 4560-4578/? V/ImapConnection: conn79097420>>> 26 NOOP
2020-10-18 01:49:23.846 4560-4578/? V/ImapResponseParser: conn79097420<<<#26# [OK, NOOP completed.]
2020-10-18 01:49:23.847 4560-4578/? V/ImapConnection: conn79097420>>> 27 UID STORE 132 +FLAGS.SILENT (\Seen)
2020-10-18 01:49:23.898 4560-4578/? V/ImapResponseParser: conn79097420<<<#27# [OK, Store completed.]
2020-10-18 01:49:23.902 4560-4578/? D/MessagingController: Done processing pending command 'com.fsck.k9.controller.MessagingControllerCommands$PendingSetFlag@48b983c'
2020-10-18 01:49:23.903 4560-4578/? I/MessagingController:  Command 'processPendingCommands' completed
2020-10-18 01:49:23.903 4560-4578/? I/MessagingController: Running command 'processPendingCommands', seq = 210 (background priority)
2020-10-18 01:49:23.903 4560-4578/? I/MessagingController:  Command 'processPendingCommands' completed
```

**Comment by cketti** [comment]
Implementing #5566 should fix this issue.
