### ISSUE TITLE
App crashes when entering in the unified inbox

### ISSUE THREAD

**Issue by ShadowBr0ther** [thunderbird/thunderbird-android#3493]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Open Unified Inbox

### Actual behavior
App crashes

### Steps to reproduce
1. Just tap on the unified inbox
2. The app crashes

### Environment
K-9 Mail version: 5.700-SNAPSHOT

Android version: 7.1.1 Nougat (LineageOS)

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
Works for me. Please provide a stack trace.

**Comment by morckx** [comment]
Same issue for me with a clean build of today:

[unified_inbox_crash.log](https://github.com/k9mail/k-9/files/2191592/unified_inbox_crash.log)

**Comment by cketti** [comment]
I believe this has been fixed.

**Comment by drder66** [comment]
This bug is back in v5.806 running on Pixel 4A. It's been around for the last couple of versions, I've just been hoping someone would notice and fix it.

Android 11, security update 5/Aug/21 Kernel 4.19.160
IMAP account type
