### ISSUE TITLE
Duplicate/Double Notifications

### ISSUE THREAD

**Issue by kmann9** [thunderbird/thunderbird-android#3795]
### Expected behavior
**One notification per single email from K9 app**

### Actual behavior
**Two duplicate notifications per single email from K9 app**

### Steps to reproduce
**Unfortunately, I am unsure how to reproduce. It seems that knowing how to reproduce this would be the answer to stopping the double notifications.**
**The problem is with all email accounts. Gmail and Yahoo. Even for emails with one label.**

### Environment
K-9 Mail version: **5.600**

Android version: **8.0.0 on S7 Edge**

Account type (IMAP, POP3, WebDAV/Exchange): **IMAP**

**Comment by aurocha** [comment]
Hi, same was happening to me with gmail. Turns I had configured the All Mail folder to notify me of new emails. So, My  folders, Inbox and All Mail were duplicating the notifications. 

Solved after turning off notifications of All Mail

**Comment by sphh** [comment]
I have the same problem on v 5.705, but I cannot find the option to turn off notifications for the Unified Inbox.

**Comment by dymn** [comment]
The same problem with v. 5.708. Very annoying.

**Comment by grmblgrmbl** [comment]
Occurs in 5.800 as well.

**Comment by cketti** [comment]
I don't think this is a bug. If you sync e.g. Gmail's "All mail" folder and the Inbox K-9 Mail will download messages in Gmail's Inbox twice. Once for the Inbox IMAP folder, and once for the "All mail" IMAP folder. K-9 Mail doesn't know they are actually the same message, because in the IMAP model they're not (in the Gmail model they are).

There's usually no need to sync the "All mail" folder. But if you do, don't enable notifications for it.

**Comment by grmblgrmbl** [comment]
But it was explictly fixed in 5.802, so....

**Comment by grmblgrmbl** [comment]
But I don't use Gmail with K-9, and for a single message in a single folder I got two notifications, until 5.802.

**Comment by sphh** [comment]
So did I … (and I am not using Gmail at all).

Anyway, it is now fixed with 5.802. Thanks @cketti !!

**Comment by Ablu** [comment]
Does someone have a reference to what was supposed to fix this in 5.802? I am still seeing this with Gmail + filters to labels. This results in messages in multiple labels at times, which causes multiple notifications for the same message.

**Comment by Koltsz** [comment]
I ran into this issue, I fixed it for me by going into:

 Settings > Accounts > my account > Fetching mail > Push folders and then changing it from **All** to **Only 1st Class folders**

I am only getting one notification now.
I'm on version 6.901
