### ISSUE TITLE
'Checking e-mail' notification in infite loop

### ISSUE THREAD

**Issue by terr72** [thunderbird/thunderbird-android#4747]
When the IMAP connection stops during a manually initiated 'checking for e-mails', the small rotating arrows in the top left notification bar and the message in the Android notification list remain there in an infinite loop.
It's also impossible to delete the message by swiping it to the left or right.
Currently I restart the phone when this happens, otherwise this drains the battery.

A solution might to implement a timeout, which both stops the 'checking for e-mails' internally and erases the animated notification icon and the message.

### Steps to reproduce
Setup an account with an unreliable server-side IMAP connection (e.g. yahoo.com) or disconnect the network connection during 'checking for e-mails'.

### Environment
K-9 Mail 5.713 on Android 10
IMAP account (yahoo.com)

**Comment by cketti** [comment]
Can you please record a debug log when this happens. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by ericJrdn** [comment]
Hi,
It seems that I have the same problem. When I wake up, I often don't get the mails I received during the night, and k9 mail is in the state described by terr72. My guess is that android 10 is doing some magic when the phone is in idle state for a long time.

I managed to fall into a similar state by playing with the connectivity of the phone : disable wifi -> check emails -> enable wifi -> check emails, etc...

Please find a log file with some stack traces.
[k9connect.txt](https://github.com/k9mail/k-9/files/4792135/k9connect.txt)

**Environment**

K-9 Mail 5.715 on Android 10
pop3 account (yahoo.com)

**Comment by ericJrdn** [comment]
Hi,
Please find a log for my device, that covers a whole night.

### Expected behavior
- The mailbox must be checked every 20 minutes
- A mail must be retrieved just after the logger start
- Another mail must be retrieved  at 08:41:45.718

### Actual behavior
- No mail was retrieved at the logger start
- No mail was retrieved at 08:41:45.718
- I can't see the polling of the mailbox

**Information :**
- Battery optimization is not enabled on k9-mail
- Somewhere around 23:57:08.570, the wifi was shutdown, and the phone switched to mobile data. At 23:57:08.570, k9mail gets the mail it was enable to get with the wifi
- At 08:41:45.758, I hit refresh, and get 'checking for e-mails' and do not receive the second mail

### Steps to reproduce
Difficult to say. Terr72 has probably the answer

### Environment
K-9 Mail version: K-9 Mail 5.715 on Android 10
Account type (IMAP, POP3, WebDAV/Exchange): pop3
[k9nuit.txt](https://github.com/k9mail/k-9/files/4796844/k9nuit.txt)

**Comment by cketti** [comment]
This should be fixed in 5.717. Can you please check and report back?

**Comment by ericJrdn** [comment]
For sure, there is still a problem. I had to kill and restart k9 a few times since your update.
[k9debug.txt](https://github.com/k9mail/k-9/files/4855898/k9debug.txt)

Here is the log file I got this night. I will give you other logs if I get them.

**Comment by terr72** [comment]
@cketti: I tried my best to trigger the error again over the last three days, but haven't had any 'luck'. It seems to be fixed, but it might also be the case, that Yahoo has increased its server resources recently so that there are less timeouts triggering the bug.

**Comment by soredake** [comment]
It's easy to trigger for me, launch app, swipe down to start refreshing, than close app, and notification stays forever.

**Comment by terr72** [comment]
soredake is spot on, same here when I manage to close the app before the refresh has finished.
Going back to the app and starting another refresh cleares the notification once it's finished.

**Comment by cketti** [comment]
The log from @ericJrdn shows there's a read timeout when the app is trying to check mails. This could be due to a network issue on the user's side, the provider's side or anywhere in between. The read timeout is 1 minute. After that the sync is canceled and the notification should disappear. I forced such a read timeout for my test device and everything worked as expected. The sync notification disappeared after 1 minute.

It might be possible that your Android versions have very aggressive memory management policies that cause the app to be killed once you "close" it. If that's the case the code that normally removes the notification is not run and the notification will just stay there. That's not great from a usability perspective. But there's no indication that K-9 Mail is running in the background all the time draining the battery.

I created issue #4862 to make sure K-9 Mail lets the system know it is still doing useful work and shouldn't be killed.

**Comment by ericJrdn** [comment]
I don't know if this logfile may be of any further help after what you said.
Currently, the notification is on the screen, and I can't retrieve new mails.
[k9debug2.txt](https://github.com/k9mail/k-9/files/4864162/k9debug2.txt)

**Comment by cketti** [comment]
@ericJrdn: That's odd. It looks like the periodic sync was canceled while it was running. And then some code probably doesn't properly recover from that. Can you please install the attached version and create another log when this happens? I enabled some additional logging (see https://github.com/k9mail/k-9/compare/5.717...5.717_workmanager_logging)

[k9mail-5.716-extra-logging.zip](https://github.com/k9mail/k-9/files/4867136/k9mail-5.716-extra-logging.zip)

**Comment by ericJrdn** [comment]
I got that tonight
[k9debugNew.txt](https://github.com/k9mail/k-9/files/4872195/k9debugNew.txt)

**Comment by ericJrdn** [comment]
similar one
[k9debugNew2.txt](https://github.com/k9mail/k-9/files/4872310/k9debugNew2.txt)

**Comment by marcoXbresciani** [comment]
I also see it, from time to time, on 5.727 from F-Droid, Android 8.0.
Actually for me it happens sometimes on the periodic sync and to stop it, so removing the notification icon, I open the app and do a manual sync (swipe down). 
When the manual sync reaches the same point of the periodic one, everything is restored and the icon disappear at the end of the manual sync.

**Comment by Dark-Noir** [comment]
+1 same here on Android 10 with 5.737, notification re-appeared after reboot. I just disabled the notification now.

**Comment by cketti** [comment]
@ericJrdn: Thanks for the logs. 

I'm still not quite sure what is happening. It looks like something is blocking the thread that all mail operations are performed on. From the logs it looks like something that shouldn't be able to happen happens. This might be me misreading the situation. It might also be a bug in the Android runtime of your device. The fact that this only happens after an exception (network error) makes me think it's the latter. What device are you using? Are you using a custom ROM?

**Comment by terr72** [comment]
@Dark-Noir Actually it's different now: I can now see a @ symbol in the notification bar after every Android start.
In the past there was only an envelope sign coming up and staying _when_ I manually asked K9 Mail to check the inbox for new messages.

**Comment by cketti** [comment]
For the `@` icon in the status bar see https://forum.k9mail.app/t/how-to-configure-push/1102

**Comment by ericJrdn** [comment]
@cketti I was using a samsung stock rom

**Comment by williamdes** [comment]
Hi @cketti 

> Currently I restart the phone when this happens, otherwise this drains the battery.

I also have since since quite some releases, it still drains my battery and heats my pocket !

I have the debug logs, but there is so much of them could I send you the log by email ?
It would be safer, it's too large for me to check for sensitive things.

**Comment by williamdes** [comment]
Hi @cketti 
What can we do to help you understand this nasty bug ?
#6322 also reports it

**Comment by williamdes** [comment]
Hi everyone

Most probably #6995 (https://github.com/thundernest/k-9/commit/07985f706688f64197dc45fef74a38f7dbbec92b) did kill this CPU/perf bug
I would advise anyone to update to https://github.com/thundernest/k-9/releases/tag/6.708 or a newer pre release (cool new stuff!)
And please let us know here if you still have the bug reported here

**Comment by terr72** [comment]
> And please let us know here if you still have the bug reported here

It seems fixed.
At least I didn't have anymore occurence since I payed close attention after your post 5 days ago.
Any comment from other users that experienced the bug in the past?

**Comment by terr72** [comment]
No more occurence in the last two weeks for me, I'll close it.

**Comment by terr72** [comment]
Hate to re-open it, but it seems to still persist in rare circumstances.
It came back twice in the last two days for me, in both case the IMAP server connections was slow/unresponsive.
To me it looks like the app doesn't recognize a timed-out connection and remains in the "checking e-mail" notification state.

Or am I alone with this?

**Comment by cketti** [comment]
@terr72: Please open a new issue if this is still a problem using the latest beta version (6.715). Make sure to include a debug log.
