### ISSUE TITLE
Broken message aborts folder sync with NullPointerException

### ISSUE THREAD

**Issue by oh2kku** [thunderbird/thunderbird-android#5093]
**Describe the bug**
When refreshing the message list of an IMAP folder that contains a message broken(?) in some way, the folder refresh aborts at the broken message. No messages that have arrived to the mailbox after the broken message, including the broken message, are displayed. Other IMAP clients like Thunderbird and Roundcube show all messages in the folder.

**To Reproduce**
1. Have a message that triggers the bug in a folder on IMAP server
2. Refresh that folder in K9
3. See the list of messages in that folder not contain messages after the broken message, including the broken message
4. Also see the exception displayed in the folder list

**Expected behavior**
No exceptions to be shown and folder message list in K9 to show all messages in the folder.

**Screenshots**
Attached is a screenshot of the folder exhibiting this issue, cropped from the folder list.
![Screenshot_20210118-025501](https://user-images.githubusercontent.com/2458254/104861933-58ef8700-593a-11eb-9154-7c4a3667d41d.jpg)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600 (latest release from Google Play Store)
 - Android version: 10 (OxygenOS 10.3.7)
 - Device: OnePlus 6T (A6013)
 - Account type: IMAP (Dovecot server)

**Additional context**
The triggering message is a malformed mime multipart/alternative spam email with text/plain and text/html parrts. Other mail clients do not seem to display what the spammer intended either, but they don't cause the folder to "freeze" to the point in time when the mail arrived, i.e. they show all other messages that arrived after the broken email.

**Logs**
Debug log starts from the point of refreshing the message list for "bugfolder", which only contains this one broken message to reduce clutter in the log. The bug also manifests itself in folders with more messages. Some identifying details of the server account and the email/address have been replaced.
[k9nullp2-redacted.txt](https://github.com/k9mail/k-9/files/5827234/k9nullp2-redacted.txt)

**Comment by cketti** [comment]
I believe this bug has been fixed already. Can you please test the latest beta version? See https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68

**Comment by oh2kku** [comment]
I tested this with the latest beta from Google Play, version 5.726. The broken message is still not shown in the folder message list, but it is not blocking seeing the later arrived messages anymore. So seems to be fixed partially.

[k9-5.726-folderrefresh2-log.txt](https://github.com/k9mail/k-9/files/5829866/k9-5.726-folderrefresh2-log.txt)

**Comment by tsager** [comment]
I do see this with K9, version 11.1 on Android 15. Log attached.
Mails after the offending message are not synced correctly (just some seem to be missing).
Deleting the offending message solves the problem and all mails synchronise fine again.

[k9mail-logs-condensed.txt](https://github.com/user-attachments/files/22580570/k9mail-logs-condensed.txt)
