### ISSUE TITLE
Folders on IMAP servers with prefixes are completely broken since 12.0b4

### ISSUE THREAD

**Issue by krzysdz** [thunderbird/thunderbird-android#9567]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.0b4, 12.0b5

### Where did you get the app from?

Other

### Android version

13 (xiaomi.eu 14.0.3.0.TJUMIXM)

### Device model

Xiaomi POCO X3 Pro (global)

### Steps to reproduce

Requires an IMAP mail server that uses prefix for non-INBOX mailboxes (e.g. GMail - #9616).

#### Variant 1 - fetching folder

1. Fetch list of folders
2. Open any folder other than _Inbox_ (e.g. _Spam_ - `INBOX.Spam`)
3. Load messages/refresh

#### Variant 2 - deleting messages

1. Make sure that there is a trash folder (e.g. `INBOX.Trash`)
2. Delete a message from inbox

#### Variant 1 - fetching folder

Messages from the selected folder are fetched from server (e.g. using command `EXAMINE "INBOX.Spam"`) and displayed.

#### Variant 2 - deleting messages

Deleted message is moved to the trash folder.

#### Variant 1 - fetching folder

Command `EXAMINE "INBOX.INBOX.Spam"` is sent and obviously fails, because there is no such folder.

#### Variant 2 - deleting messages

Command similar to `UID MOVE 27707:27708,27714:27715 "INBOX.INBOX.Trash"` (here I was deleting multiple messages) is sent and also fails. This leads to a desync, because messages end up in the local trash, disappearing from inbox, but still exist on server and are shown to other clients.

I was wondering why desktop Thunderbird and webmail showed 15 more unread messages than Thunderbird for Android and thought it is a weird sync problem.

### Regression analysis

This regression is caused by #9241 that was uplifted to beta in #9523 (I guess now some of the associated risk is known) and released in 12.0b4.

`serverId` is _absolute_ - it includes folder name including the prefix. Previously most folder `serverId`s were "old server IDs" and [had the prefix removed](https://github.com/thunderbird/thunderbird-android/commit/74cbed1bdb1375cb15014b16cd75463b48f60071#diff-b88fcb0b0a4fbe9cda33c13ffc19bf81f7bc110a545cf81e24c87532fdef03b5L193-L203). Now folders are initialised with `serverId` that contains prefix, but commands either use `encodedName` which is just [`folderNameCodec.encode(prefixedName)`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L98-L102) or directly call `folderNameCodec.encode(folder.prefixedName)` ([`copyMessages`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L309-L310) and [`moveMessagesUsingMoveExtension`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L345-L346)) - in either case [`prefixedName`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L73-L96) is used and [`prefixedName`](https://github.com/thunderbird/thunderbird-android/blob/5a296ceaccbb5c4976cd109119f8a6135c376b40/mail/protocols/imap/src/main/java/com/fsck/k9/mail/store/imap/RealImapFolder.kt#L73-L96) prefixes the `serverId` (that already has prefix).

### Logs

<details>
<summary>
Logs showing refreshing folders list (<code>LIST</code> command) and an attempt at fetching spam folder content (<code>EXAMINE</code>)
</summary>

```log
08-04 23:19:05.601 23247  7026 I MessagingController: Running command 'refreshFolderList', seq = 33 (foreground priority)
08-04 23:19:05.609 23247  7026 V RealImapConnection: conn9763719>>> 5 NOOP
08-04 23:19:05.677 23247  7026 V ImapResponseParser: conn9763719<<<#5# [OK, NOOP completed.]
08-04 23:19:05.690 23247  7026 V RealImapConnection: conn9763719>>> 6 LIST "" "INBOX.*" RETURN (SPECIAL-USE)
08-04 23:19:05.703 23247 23247 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 23:19:05.715 23247 23247 I HandWritingStubImpl: refreshLastKeyboardType: 1
08-04 23:19:05.715 23247 23247 I HandWritingStubImpl: getCurrentKeyboardType: 1
08-04 23:19:05.768 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Drafts], ., INBOX.Drafts]
08-04 23:19:05.785 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Junk], ., INBOX.Spam]
08-04 23:19:05.800 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Sent], ., INBOX.Sent Items]
08-04 23:19:05.814 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [\Trash], ., INBOX.Trash]
08-04 23:19:05.828 23247  7026 V ImapResponseParser: conn9763719<<<#null# [LIST, [], ., INBOX.Templates]
08-04 23:19:05.837 23247  7026 V ImapResponseParser: conn9763719<<<#6# [OK, List completed.]
08-04 23:19:05.930 23247  7026 I K9StorageEditor: Committing preference changes
08-04 23:19:05.987 23247  7027 D OpenGLRenderer: endAllActiveAnimators on 0xb4000079135b5000 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000798156a080
08-04 23:19:05.999 23247  7026 I K9StorageEditor: Preferences commit took 68 ms
08-04 23:19:06.058 23247  7030 V PushController: PushController.updatePushers()
08-04 23:19:06.124 23247  7026 I K9StorageEditor: Committing preference changes
08-04 23:19:06.178 23247  7026 I K9StorageEditor: Preferences commit took 57 ms
08-04 23:19:06.232 23247  7026 D MessagingController: Folder list successfully refreshed @ Mon Aug 04 23:19:06 CEST 2025
08-04 23:19:06.241 23247  7030 V PushController: ..Running PushControllers: [0308d0e4-7659-46d8-befe-ec78911c1b7d]
08-04 23:19:06.269 23247  7026 I K9StorageEditor: Committing preference changes
08-04 23:19:06.350 23247  7026 I K9StorageEditor: Preferences commit took 81 ms
08-04 23:19:06.390 23247  7026 I MessagingController:  Command 'refreshFolderList' completed
08-04 23:19:06.411 23247  7030 V PushServiceManager: PushServiceManager.start()
08-04 23:19:06.419 23247  7030 V PushServiceManager: ..PushService already running
08-04 23:19:06.426 23247  7030 V BootCompleteManager: Enable BootCompleteReceiver
08-04 23:19:06.436 23247  7030 V PushController: PushController.updatePushers()
08-04 23:19:06.447 23247  7030 V PushController: ..Running PushControllers: [0308d0e4-7659-46d8-befe-ec78911c1b7d]
08-04 23:19:06.465 23247  7030 V PushServiceManager: PushServiceManager.start()
08-04 23:19:06.468 23247  7030 V PushServiceManager: ..PushService already running
08-04 23:19:06.471 23247  7030 V BootCompleteManager: Enable BootCompleteReceiver
08-04 23:19:06.477 23247  7030 V PushController: PushController.updatePushers()
08-04 23:19:06.483 23247  7030 V PushController: ..Running PushControllers: [0308d0e4-7659-46d8-befe-ec78911c1b7d]
08-04 23:19:06.493 23247  7030 V PushServiceManager: PushServiceManager.start()
08-04 23:19:06.496 23247  7030 V PushServiceManager: ..PushService already running
08-04 23:19:06.500 23247  7030 V BootCompleteManager: Enable BootCompleteReceiver
08-04 23:19:07.987 23247 23247 D MIUIInput: [KeyEvent] ViewRootImpl windowName 'net.thunderbird.android.debug/com.fsck.k9.ui.managefolders.ManageFoldersActivity', KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=90282514000000, downTime=90282514000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=23:19:07.891
08-04 23:19:08.008 23247 23247 D MIUIInput: [KeyEvent] ViewRootImpl windowName 'net.thunderbird.android.debug/com.fsck.k9.ui.managefolders.ManageFoldersActivity', KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=90282571000000, downTime=90282514000000, deviceId=-1, source=0x101, displayId=0 }, phoneEventTime=23:19:07.948
08-04 23:19:08.180 23247  7026 I MessagingController: Running command 'clearNotifications', seq = 34 (foreground priority)
08-04 23:19:08.191 23247  7026 V NotificationController: Removing some notifications for account 0308d0e4-7659-46d8-befe-ec78911c1b7d
08-04 23:19:08.195 23247 23247 D DecorView[]: onWindowFocusChanged hasWindowFocus false
08-04 23:19:08.199 23247  7026 I MessagingController:  Command 'clearNotifications' completed
08-04 23:19:08.279 23247 23247 D VRI[MessageList]: vri.reportNextDraw android.view.ViewRootImpl.performTraversals:2957 android.view.ViewRootImpl.doTraversal:36 android.view.ViewRootImpl$TraversalRunnable.run:7 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:20
08-04 23:19:08.280 23247 23247 D VRI[MessageList]: vri.Setup new sync id=7 syncSeqId=0
08-04 23:19:08.469 23247 23247 D VRI[MessageList]: vri.reportDrawFinished syncSeqId=0 android.view.ViewRootImpl.lambda$createSyncIfNeeded$4$android-view-ViewRootImpl:5 android.view.ViewRootImpl$$ExternalSyntheticLambda1.run:6 android.os.Handler.handleCallback:2 android.os.Handler.dispatchMessage:4 android.os.Looper.loopOnce:182
08-04 23:19:08.544 23247 23247 D MessageListViewModel: Received new MessageListInfo: MessageListInfo(messageListItems=[], hasMoreMessages=true)
08-04 23:19:08.546 23247 23247 D DecorView[]: onWindowFocusChanged hasWindowFocus true
08-04 23:19:08.559 23247 23247 I HandWritingStubImpl: refreshLastKeyboardType: 1
08-04 23:19:08.559 23247 23247 I HandWritingStubImpl: getCurrentKeyboardType: 1
08-04 23:19:10.953 23247  7026 I MessagingController: Running command 'loadMoreMessages', seq = 35 (background priority)
08-04 23:19:10.974 23247  7026 D MessagingController: Last folder list refresh @ Mon Aug 04 23:19:06 CEST 2025. Not refreshing now.
08-04 23:19:10.992 23247  7026 I ImapSync: Synchronizing folder konto.pl:INBOX.Spam
08-04 23:19:10.998 23247  7026 V ImapSync: SYNC: About to get local folder INBOX.Spam
08-04 23:19:11.012 23247  7026 V ImapSync: SYNC: About to get remote folder INBOX.Spam
08-04 23:19:11.019 23247  7026 V ImapSync: SYNC: About to open remote folder INBOX.Spam
08-04 23:19:11.028 23247  7026 V RealImapConnection: conn9763719>>> 7 NOOP
08-04 23:19:11.119 23247  7026 V ImapResponseParser: conn9763719<<<#7# [OK, NOOP completed.]
08-04 23:19:11.131 23247  7026 V RealImapConnection: conn9763719>>> 8 EXAMINE "INBOX.INBOX.Spam"
08-04 23:19:11.201 23247  7026 V ImapResponseParser: conn9763719<<<#8# [NO, Mailbox doesn't exist: INBOX.INBOX.Spam]
08-04 23:19:11.221 23247  7026 E RealImapFolder: Unable to open connection for 0308d0e4-7659-46d8-befe-ec78911c1b7d:INBOX.Spam/MessagingController/conn9763719
08-04 23:19:11.221 23247  7026 E RealImapFolder: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE "INBOX.INBOX.Spam"; response: #8# [NO, Mailbox doesn't exist: INBOX.INBOX.Spam]
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:127)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:747)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:733)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:106)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:146)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:117)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:84)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:56)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:658)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:596)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.loadMoreMessagesSynchronous(MessagingController.java:560)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.lambda$loadMoreMessages$4$com-fsck-k9-controller-MessagingController(MessagingController.java:544)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:239)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(Unknown Source:0)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:179)
08-04 23:19:11.221 23247  7026 E RealImapFolder:        at java.lang.Thread.run(Thread.java:1012)
08-04 23:19:11.236 23247  7026 E ImapSync: synchronizeMailbox
08-04 23:19:11.236 23247  7026 E ImapSync: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE "INBOX.INBOX.Spam"; response: #8# [NO, Mailbox doesn't exist: INBOX.INBOX.Spam]
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:127)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:747)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:733)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:106)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:146)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:117)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:84)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:56)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:658)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:596)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.loadMoreMessagesSynchronous(MessagingController.java:560)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.lambda$loadMoreMessages$4$com-fsck-k9-controller-MessagingController(MessagingController.java:544)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:239)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(Unknown Source:0)
08-04 23:19:11.236 23247  7026 E ImapSync:      at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:179)
08-04 23:19:11.236 23247  7026 E ImapSync:      at java.lang.Thread.run(Thread.java:1012)
08-04 23:19:11.259 23247  7026 E ImapSync: Failed synchronizing folder konto.pl:INBOX.Spam @ Mon Aug 04 23:19:11 CEST 2025
08-04 23:19:11.267 23247  7026 I MessagingController:  Command 'loadMoreMessages' completed
```

</details>

<details>
<summary>
Logs showing failed message removal (moving to trash)
</summary>

```
08-04 21:02:52.606 22513 31526 V RealImapConnection: conn83236368>>> 191 UID MOVE 27707:27708,27714:27715 "INBOX.INBOX.Trash"
08-04 21:02:52.653 22513 31526 V ImapResponseParser: conn83236368<<<#191# [NO, [TRYCREATE], Mailbox doesn't exist: INBOX.INBOX.Trash]
08-04 21:02:52.655 22513 31526 E MessagingController: Failure of command 'move_and_mark_as_read' was permanent, removing command from queue
08-04 21:02:52.655 22513 31526 E MessagingController: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID MOVE 27707:27708,27714:27715 "INBOX.INBOX.Trash"; response: #191# [NO, [TRYCREATE], Mailbox doesn't exist: INBOX.INBOX.Trash]
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:127)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:747)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:733)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeCommandWithIdSet(RealImapConnection.kt:770)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.moveMessagesUsingMoveExtension(RealImapFolder.kt:350)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.moveMessages(RealImapFolder.kt:335)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveOrCopyMessages(CommandMoveOrCopyMessages.kt:59)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveMessages(CommandMoveOrCopyMessages.kt:15)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.moveMessagesAndMarkAsRead(ImapBackend.kt:104)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:932)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.processPendingMoveAndRead(MessagingController.java:902)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingControllerCommands$PendingMoveAndMarkAsRead.execute(MessagingControllerCommands.java:94)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:752)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController$3.run(MessagingController.java:722)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:239)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:179)
08-04 21:02:52.655 22513 31526 E MessagingController: 	at java.lang.Thread.run(Thread.java:1012)
```

</details>

**Comment by GerryArqIT** [comment]
Same issue here, 12.0b4 installed on Samsung S25 from Google Play, logs showing same issue.

**Comment by krzysdz** [comment]
I tried replacing[^1] `prefixedName` with `serverId` and everything that I've checked seems to work (fetching messages, deleting, moving, copying, adding/removing flags (seen and starred)).

[^1]: What I really did for test was just adding `return serverId` as the first line of `prefixedName` getter.

**Comment by GerryArqIT** [comment]
For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.

**Comment by azlux** [comment]
Thank for the workaround @GerryArqIT , it's working well (just the name for folder are replaced with imap path, but it's ok until a futur fix)

**Comment by 7lives83** [comment]
Same Here.. with dovecot IMAP Servers.

**Comment by masayuki-nakano** [comment]
I see this bug with Courier IMAP which is used by one of the most famous rental server companies in Japan.

**Comment by 7lives83** [comment]
Sorry guys.. but this is a high priority bug. this is happens at the moment to many users. nobody of them can see their e-mails in folgers in the client. looks always empty. two of my friends got the same problem.
and no: they dont want to change the imap prefix.. deinstall 🫩😢🫣

**Comment by SchugyC** [comment]
Thanks for the workaround. Works flawlessly with freenet.de, be-webspace.DE and t-online.de. I hope the fallback lands in the next minor release: If no Prefix is detected accept none "" as valid server answer.

**Comment by PeeK1e** [comment]
> For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.

~~Where would you set this option?
I can't find it in the K9/thunderbird settings nor do I host the mailserver so there is very limited stuff I can do server side.~~

Found it: _Settings > account > fetching mail > incoming server_

**Comment by aereaux** [comment]
> > For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.
> 
> Where would you set this option? I can't find it in the K9/thunderbird settings nor do I host the mailserver so there is very limited stuff I can do server side.

In the account settings, under Fetching mail -> Incoming server.

It would be really great to get an actual fix for this issue, though.  It was really not obvious why things stopped working.

**Comment by krzysdz** [comment]
> Where would you set this option?
 

Settings -> select account -> Fetching mail -> Incoming server\
The relevant options are at the bottom, uncheck "Auto-detect IMAP namespace".

**Comment by PeeK1e** [comment]
> It would be really great to get an actual fix for this issue, though. It was really not obvious why things stopped working.

Yeah I was confused why I could not load any mails in my spam folder as well as why deleting mails didn't sync to the server

**Comment by Chatter35** [comment]
Similar and **very unpleasant issue** here. Thunderbird 12.1 on Pixel 9 Pro XL with GrapheneOS-Android 16.
However, this issue does not apply with all my email-services. **While some email-services work well, others do not sync properly (in my case ...@t-online.de)**. What I see is the following when using Thunderbird latest versions on both Mac and Android:

Read mail on Android - marked as read on Mac (thus all fine so far)
Delete mail on Android - gets **NOT** deleted on Mac (**sync issue!**)
Moving mail on Android from inbox to another folder - gets **Not** moved on Mac (**sync issue!**)
Moving mail on Mac to another folder - gets removed from Android (**sync issue!**). In other words - all mails moved on Mac from inbox to a folder **are gone on the Android**. This is a really unpleasant.

Note: All **these issues do NOT appear with Thunderbird v11.1**. Thus, for the moment I have switched back to that version on my Android.

**Comment by pglpm** [comment]
> For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.

Solved for me as well. Thank you!

**Comment by binki** [comment]
The affected version is on Play Store now: https://forum.k9mail.app/t/-/13509

**Comment by Chatter35** [comment]
> For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.

Thank you! The workaround works for me as well. 
However, I you have moved a mail on the Android BEFORE disabling "Auto-detect IMAP namespace", this particular mail will NOT be synced AFTER disabling "Auto-detect IMAP namespace". In stead, you will get a copy of that mail.
Thx again for your hint.

**Comment by arxo** [comment]
@GerryArqIT's workaround did the trick for me as well. Many, many thanks! :-)

**Comment by binki** [comment]
> > For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.
> 
> Thank you! The workaround works for me as well. However, I you have moved a mail on the Android BEFORE disabling "Auto-detect IMAP namespace", this particular mail will NOT be synced AFTER disabling "Auto-detect IMAP namespace". In stead, you will get a copy of that mail. Thx again for your hint.

Be careful with that copy! I am pretty sure that the “copy” you see in K9/Thunderbird Android is just a ghost. Check this by opening the message and then attempting to move it somewhere—a ghost will give you the error about the message not being synchronized to the server. Don’t delete the other one—you might permanently lose it whenever the ghost copy gets cleaned up!

**Comment by Chatter35** [comment]
> > > For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.
> > 
> > 
> > Thank you! The workaround works for me as well. However, I you have moved a mail on the Android BEFORE disabling "Auto-detect IMAP namespace", this particular mail will NOT be synced AFTER disabling "Auto-detect IMAP namespace". In stead, you will get a copy of that mail. Thx again for your hint.
> 
> Be careful with that copy! I am pretty sure that the “copy” you see in K9/Thunderbird Android is just a ghost. Check this by opening the message and then attempting to move it somewhere—a ghost will give you the error about the message not being synchronized to the server. Don’t delete the other one—you might permanently lose it whenever the ghost copy gets cleaned up!

Yes, it's a ghost, in fact - I have used the same approach as you to detect the ghost copy - which then can be deleted on the Android.

**Comment by pglpm** [comment]
> Be careful with that copy! I am pretty sure that the “copy” you see in K9/Thunderbird Android is just a ghost.

*Possibly* it can be useful to do a refresh with:
- "Manage folders" (at the bottom of the folder list)
- -> choose a problematic folder
- -> in "Folder Settings" for that folder, choose "Clear local messages" in the three-dot menu on the upper right.

I say **possibly**; that's what I did. But I don't know if this could make things worse.

**Comment by kvibber** [comment]
I wonder if this is why 12.1 won't retrieve any of my mail from my primary IMAP account on DreamHost.

**Comment by coreycb** [comment]
Confirmed based on multiple reports.

**Comment by Z-Brox** [comment]
> For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.

Stumbled upon the issue in 12.1. Thank you @GerryArqIT for the workaround.

**Comment by jcharaoui** [comment]
>  Be careful with that copy! I am pretty sure that the “copy” you see in K9/Thunderbird Android is just a ghost.

Before enabling the workaround mentioned here, I used Thunderbird to send a few emails, and noticed something was probably wrong because those messages weren't showing up on my other IMAP client (Roundcube).

Now, after disabling the prefix auto-detect, I can see all the messages on the IMAP server, but the "local" messages that I sent with Thunderbird weren't uploaded to IMAP. When I try to move or copy them, I get an error message about being unable to copy or move while the message isn't synchronised, even though I'm online all the time.

I'm hoping the fix here will include dealing with these "local-only" message that seem to be stuck in some kind of purgatory...

**Comment by coreycb** [comment]
There is a fix for this on 13.0b2 if anyone wants to give it some testing

**Comment by ivnmad** [comment]
13.0b2 solves the issue.

**Comment by uschindler** [comment]
Hi,
I installed the beta version and imported older settings (before 12, about a year old). The special folders were preserved (see other issue #9771). Fetching Mail also worked from all folders.
It looks like it's fixed.

**Comment by cayhorstmann** [comment]
> For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.

The workaround works for me on FastMail, thanks so much! It's a little ugly that all the folder names now start with INBOX.

**Comment by GerryArqIT** [comment]
> > For info: there's a workaround for this issue, at least in my case. For those accounts where this issue occurred - they were all on the same server - after disabling "Auto-detect IMAP namespace" and leaving IMAP path prefix empty, the problem is gone.
> 
> The workaround works for me on FastMail, thanks so much! It's a little ugly that all the folder names now start with INBOX.

@cayhorstmann  The newest available version fixed this issue, update to it and you can undo the workaround again.

**Comment by aereaux** [comment]
The newest version is 12.1, I think?  I don't think it includes [the fix](https://github.com/thunderbird/thunderbird-android/pull/9772), right?

**Comment by jcharaoui** [comment]
I doesn't appear like a release has been made since the fix was merged, unfortunately.

**Comment by GerryArqIT** [comment]
Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.

**Comment by jebbgrenham** [comment]
Any hope of a fix? I'm trying to sync a month or so of sent messages, deletions which are currently still trying to sync but don't. Removing the auto prefix and leaving the prefix blank doesn't solve the bug for me.

**Comment by jcharaoui** [comment]
According to the release calendar, stable version 13.0 should be released next Monday, and will likely include the fix.

**Comment by jebbgrenham** [comment]
Is there any way to get this version (to replace current stable) without waiting a week? I would like to clear this massive backlog; and the workaround using IMAP prefix doesn't work.

**Comment by webracer999** [comment]
@jebbgrenham 

> Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.

**Comment by binki** [comment]
@webracer999 
> [@jebbgrenham](https://github.com/jebbgrenham)
> 
> > Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.

Does that app use the data store of the main app or will people with pending deletes/renames/saves need to manually re-make all of those changes manually? I assume that the beta app would be installed side-by-side and you wouldn’t be able to move your pending actions from the real app to that.

Also, for people who made moves and saved drafts or sent messages on the buggy version of the app, will those moves go through after the update or are those actions all “infected” with the bad folder names and going to remain failed after updating to the fixed version on Monday?

**Comment by jebbgrenham** [comment]
> [@jebbgrenham](https://github.com/jebbgrenham)
> 
> > Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.

This doesn't work. It installs alongside the stable version, and even after importing settings from the local app, it syncs what's ON the IMAP server, it does not import the queued actions.

**Comment by jebbgrenham** [comment]
> > [@jebbgrenham](https://github.com/jebbgrenham)
> > > Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.
> 
> This doesn't work. It installs alongside the stable version, and even after importing settings from the local app, it syncs what's ON the IMAP server, it does not import the queued actions.

I also tried installing via the APK but android still sees it as a separate app; not able to replace (and use same data store) as the stable version. Is there some way to use the beta app to REPLACE the stable?

**Comment by coreycb** [comment]
We are planning for a 13.0 release next week if you are able to hold off until then.

**Comment by rafaeltonholo** [comment]
> > > [@jebbgrenham](https://github.com/jebbgrenham)
> > > > Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.
> > 
> > 
> > This doesn't work. It installs alongside the stable version, and even after importing settings from the local app, it syncs what's ON the IMAP server, it does not import the queued actions.
> 
> I also tried installing via the APK but android still sees it as a separate app; not able to replace (and use same data store) as the stable version. Is there some way to use the beta app to REPLACE the stable?

Hi there,

The beta app has a different package name and signature than the stable app, which means that, to the Android OS, they are recognized as two separate applications. Therefore, they cannot replace each other.

In the meantime, until we release version 13, I kindly ask that you use the beta version. We are still conducting tests, and we plan to release the stable version on next week, provided we don’t encounter any further issues.

Thank you for your understanding.

**Comment by jebbgrenham** [comment]
> > > > [@jebbgrenham](https://github.com/jebbgrenham)
> > > > > Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.
> > > 
> > > 
> > > This doesn't work. It installs alongside the stable version, and even after importing settings from the local app, it syncs what's ON the IMAP server, it does not import the queued actions.
> > 
> > 
> > I also tried installing via the APK but android still sees it as a separate app; not able to replace (and use same data store) as the stable version. Is there some way to use the beta app to REPLACE the stable?
> 
> Hi there,
> 
> The beta app has a different package name and signature than the stable app, which means that, to the Android OS, they are recognized as two separate applications. Therefore, they cannot replace each other.
> 
> In the meantime, until we release version 13, I kindly ask that you use the beta version. We are still conducting tests, and we plan to release the stable version on next week, provided we don’t encounter any further issues.
> 
> Thank you for your understanding.

This doesn't fix the problem; as the beta uses a different database (ie doesn't share a database with the stable version). Currently, everyone's Thunderbird app has a queued list of deletions, and a bunch of unsynced messages waiting to sync with the server, which can't happen until the fix is included in stable. Installing the beta app just gives a working copy of the app which does **not** include the unsynced messages.

**Comment by jebbgrenham** [comment]
> > > > > [@jebbgrenham](https://github.com/jebbgrenham)
> > > > > > Use the "Thunderbird Beta for Testers" app on Google Play, version 13.0b4 available with the fix.
> > > > 
> > > > 
> > > > This doesn't work. It installs alongside the stable version, and even after importing settings from the local app, it syncs what's ON the IMAP server, it does not import the queued actions.
> > > 
> > > 
> > > I also tried installing via the APK but android still sees it as a separate app; not able to replace (and use same data store) as the stable version. Is there some way to use the beta app to REPLACE the stable?
> > 
> > 
> > Hi there,
> > The beta app has a different package name and signature than the stable app, which means that, to the Android OS, they are recognized as two separate applications. Therefore, they cannot replace each other.
> > In the meantime, until we release version 13, I kindly ask that you use the beta version. We are still conducting tests, and we plan to release the stable version on next week, provided we don’t encounter any further issues.
> > Thank you for your understanding.
> 
> This doesn't fix the problem; as the beta uses a different database (ie doesn't share a database with the stable version). Currently, everyone's Thunderbird app has a queued list of deletions, and a bunch of unsynced messages waiting to sync with the server, which can't happen until the fix is included in stable. Installing the beta app just gives a working copy of the app which does **not** include the unsynced messages.

I'm guessing that the fix short term is to
1. Clone the main branch from git
2. Build a package marked stable
3. Somehow make a backup of the queued (unsynced) installation - more research needed on how to this.
4. Install on phone
5. On Monday, install the app from play store again, replacing the temporary build
I'll report back if this works....

**Comment by jebbgrenham** [comment]
It looks like this wasn't released on Monday as scheduled. Github shows no releases and play store and f-droid still have v12. Anyone know what's up?

**Comment by krzysdz** [comment]
> It looks like this wasn't released on Monday as scheduled. Github shows no releases and play store and f-droid still have v12. Anyone know what's up?

The release was delayed by a week:

<img width="1097" height="154" alt="Matrix message dated 2025-10-08T16:22:01Z: With the shift of 13.0 and 14.0b1 to Oct 20, the soft freeze is also shifted and will start tomorrow." src="https://github.com/user-attachments/assets/71615c51-f465-4c13-88b4-fe44f1f0554d" />

The [milestones](https://github.com/thunderbird/thunderbird-android/milestones) seem to have currently planned release dates:

<img width="158" height="187" alt="GitHub milestones and their due dates. Thunderbird 15 - December 8; Thunderbird 14 - October 27; Thunderbird 13 - October 20" src="https://github.com/user-attachments/assets/7ff53722-f964-42ef-9582-da9a49edda20" />

**Comment by MDKAOD** [comment]
Hi all,
I'm still seeing this issue with Version 13. Changes made within the app still do not sync with IMAP folders. (Outgoing emails, mark as read, & deletes in my usage)

IMAP prefix workaround is not working for me.

**Comment by starox** [comment]
Hello @MDKAOD ,

> Hi all, I'm still seeing this issue with Version 13. Changes made within the app still do not sync with IMAP folders. (Outgoing emails, mark as read, & deletes in my usage)
> 
> IMAP prefix workaround is not working for me.

This version fixes the problem for me. Have you enable "Auto-detect IMAP namespace"  on your account ?

**Comment by jebbgrenham** [comment]
It's working for **new** deletions and **newly sent** messages (after updating to 13). I enabled "Auto-detect IMAP namespace" before I checked if it was working without doing that.

However... whoever wrote this fix (thanks, but...) instead of processing all the queued deletions from the phone to the server, it UN-deleted all the locally deleted messages and **put them back in the inbox** (ie; it just discarded all the queued deletions and resynced the inbox from the IMAP server). Unfortunately for everyone who has auto updates on android, presumably this deletion queue is now unrecoverable if thunderbird has already updated? Everyone using IMAP (most of the userbase?) now probably collectively has millions of e-mail messages to manually delete (again) over the coming days.

Fortunately, all the SENT messages did sync TO the server; so they got half of the fix right. I don't use other subfolders so I can't comment on that.

If you haven't received the TB update, you may be wise to avoid it and hope that this bug gets fixed in a near future release. If you HAVE received the update but your deleted messages have not reappeared in your inbox; perhaps leave the "Auto-detect IMAP namespace" unchecked for now and hope that this bug is addressed promptly. Fingers crossed.
