### ISSUE TITLE
Notification Sounds Stopped

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#9645]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.0b7

### Where did you get the app from?

Google Play

### Android version

16

### Device model

Pixel 8 Pro

### Steps to reproduce

1. Start device
2. Receive mail
3. Wait a few hours 
4. Receive more mail

### Expected behavior

You hear the new mail notification sound

### Actual behavior

Nothing.

### Logs

[k9mail-logs (2).txt](https://github.com/user-attachments/files/21972751/k9mail-logs.2.txt)

**Comment by uniquePWD** [comment]
No one else seeing this?

**Comment by Vladimyr0** [comment]
I've had not the same, but something similar: on clean install it was very difficult to get any sound on receiving a mail. 
turning notifications off and on, changing melody, switching do-not-disturb mode and so on, 
I got, finally, sound working after a couple of days. 
I didn't figure out how I was able to solve the problem, but somehow I was :)
and now the sound is working fine, at least for two weeks.

**Comment by uniquePWD** [comment]
I uninstalled and reinstalled to fix my issue

**Comment by DaleBCooper** [comment]
This looks like a regression between 11.1 and 12.x

With latest version 12.1 on Android 16 (Graphene OS, October patch) and Android 15 (September patch) the new mail notification on new mail is shown but silently without sound and vibration.
Both vibration and sound are turned on.

On both phones  new mail notifications work as expected with vibration and the configured sound.

**Comment by JackMauro** [comment]
I have the same issue as DaleBCooper on android 15, august patch

**Comment by noguespi** [comment]
I have the exact same issue, Pixel 7a, Android 16 Grapheneos  20251009,  Thunderbird 12.1.

The notification itself works, it is received by the phone (so it is not a push/sync issue). But it remains silent most of the time, (sometime it trigger the sound, but is is rare).

Only Thunderbird app is impacted, notification sounds works on other apps. 

Uninstalling/reinstalling doesn't solve the issue.

**Comment by noguespi** [comment]
I've been using v11.1 for a few days and notification sounds works perfectly. So the issue is likely to only impact v12+

**Comment by uniquePWD** [comment]
It's fixed in 13, so only 12 was affected.

**Comment by DaleBCooper** [comment]
Not fixed. After about one day the notifications have lost sound and vibration again, same as in version 12.
I have updated to version 13 yesterday and at first it looked promising.

**Comment by DaleBCooper** [comment]
Just in case someone with this problem reads here, the issues is caused by a bug in "Quiet Time" settings. See #10007

**Comment by noguespi** [comment]
Guys what version are you using and is the issue fixed ? #10007 is still open so I don't think so.

I'm still using v11, I did try v12 and v13 but notification didn't worked with these versions. Did someone try v14 or v15 ?

**Comment by uniquePWD** [comment]
> Guys what version are you using and is the issue fixed ? [#10007](https://github.com/thunderbird/thunderbird-android/issues/10007) is still open so I don't think so.
> 
> I'm still using v11, I did try v12 and v13 but notification didn't worked with these versions. Did someone try v14 or v15 ?

It's fixed in 13+. If you're still seeing problems in 13 or above, it's likely a different bug.

**Comment by DaleBCooper** [comment]
Confirm. No Problems since 13+.
This bug and #10007 should be closed.
